version: "3"

services:
  pooler:
    cpuset: "0-3"
    build: ./pgbouncer
    ports:
      - "6543:6543"
    depends_on:
      - postgres

  pgbench:
    command: >
      bash -c '
      sleep 5;
      pgbench -i "postgres://postgres:postgres@pooler:6543/postgres?sslmode=disable";
      pgbench "postgres://postgres:postgres@pooler:6543/postgres?sslmode=disable" -Srn -T 60 -j 8 -c 10 -P 10 -M extended'
