version: "3"

services:
  postgres:
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      HOST: "postgres"

  pgbouncer:
    build: ./pgbouncer
    ports:
      - "6543:6543"
    depends_on:
      - postgres

  #  supavisor:
  #    build: ./supavisor
  #    depends_on:
  #      - postgres

  pgbench:
    build: ./pgbench
    depends_on:
      - pgbouncer

volumes:
  pgdata:
