version: "3"

services:
  postgres:
    cpuset: "3-6"
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      HOST: "postgres"

  pgbench:
    cpuset: "7-9"
    build: ./pgbench
    depends_on:
      - pooler
      - postgres

volumes:
  pgdata:
