version: "3"

services:
  postgres:
    build: ./postgres
    # environment:
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgbouncer:
    build: ./pgbouncer
    # environment:
    depends_on:
      - postgres
volumes:
  pgdata:
