version: "3"

services:
  supavisor_db:
    image: postgres:15
    volumes:
      - ./supavisor/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres

  pooler:
    build: ./supavisor
    depends_on:
      - postgres
      - supavisor_db
  pgbench:
    command: >
      bash -c '
      sleep 10;
      pgbench -i "postgres://postgres.dev_tenant:postgres@pooler:6543/postgres?sslmode=disable";
      pgbench "postgres://postgres.dev_tenant:postgres@pooler:6543/postgres?sslmode=disable" -Srn -T 60 -j 8 -c 300 -P 10 -M extended'



