version: "3"

services:
  postgres:
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgbouncer:
    build: ./pgbouncer
    ports:
      - "6543:6543"
    depends_on:
      - postgres

volumes:
  pgdata:
