version: "3"

services:
  pooler:
    cpuset: "0-3"
    build: ./supavisor
    depends_on:
      - postgres

  pgbench:
    command: >
      bash -c '
      sleep 10;
      pgbench -i "postgres://postgres.dev_tenant:postgres@pooler:6543/postgres?sslmode=disable";
      pgbench "postgres://postgres.dev_tenant:postgres@pooler:6543/postgres?sslmode=disable" -Srn -T 60 -j 8 -c 10 -P 10 -M prepared'
